### ISSUE TITLE
GnuTLS error: #<process twitchemotes.com>, -12

### ISSUE THREAD

**Issue by troublew** [vibhavp/erc-twitch#2]
Hie, 
when I activate the mod in erc, this bug appear:
GnuTLS error: #<process twitchemotes.com>, -12

When I try this command: (url-retrieve-synchronously "https://twitchemotes.com/api_cache/v2/global.json")
in ielm, this is what I get as an error:
gnutls.el: (err=[-12] A TLS fatal alert has been received.) boot: (:priority NORMAL :hostname twitchemot.com :loglevel 0 :min-prime-bits 256 :trustfiles (/etc/ssl/certs/ca-certificates.crt) :crlfiles nil :keylist nil :verify-flags nil :verify-error nil :callbacks nil)

But url-retrieve-synchronously work if I indicate another url.
Thanks you a lot for the mod!

**Comment by vibhavp** [comment]
hm, are you still having this issue? I could change the URLs to use HTTP instead of HTTPS

**Comment by troublew** [comment]
I still have the issue, even with a simple http request.
I have just done a little workout just for me:

```
(defun erc-twitch--get-emotes-json ()
  (let ((json-object-type 'hash-table))
    (with-current-buffer
    (url-retrieve-synchronously "file:///home/a/certain/path/global.json")
      (json-read))))
```

I have downloaded manually the json file (hope I don't need to update it too often, or I'll just automate the download)
I really don't know if the problem comes only from me. But still every other links work, exept this website... I don't know why at all.
I don't think that you have to change anything, especially if you cannot reproduce the error.
Anyway, thanks for the mod!

**Comment by ameuret** [comment]
Seeing same thing here on GNU EMACS 24.5.1. Used that workaround.

**Comment by jwdoran** [comment]
I'm getting this error even with the HTTP URLs.

**Comment by jwdoran** [comment]
I found this thread: http://emacs.1067599.n8.nabble.com/bug-20465-24-4-GnuTLS-integration-seems-faulty-td357111.html

According to the thread there was a bug fixed in emacs 25 that resolves this issue.

Upgrading emacs removed the errors for me.
