### ISSUE TITLE
Warnings on installation

### ISSUE THREAD

**Issue by jwdoran** [vibhavp/erc-twitch#5]
I have 3 warnings when installing this package:
```
erc-twitch.el:58:62:Warning: reference to free variable
    `url-http-end-of-headers'
erc-twitch.el:93:1:Warning: Unused lexical variable `end-pos'
erc-twitch.el:93:1:Warning: Unused lexical variable `start-pos'
```

Ultimately the option `erc-twitch-enable` is not available after the install and I suspect this might be related to the warningins above.

**Comment by vibhavp** [comment]
They're just warnings, so they should not affect the installation. Did you
add (require 'erc-twitch) before enabling the module?

**Comment by jwdoran** [comment]
After I ran `(require 'erc-twitch)` the features were enabled.  Thanks.
